version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=redsanitaria
      - POSTGRES_DATABASE=test_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/schemas/createPostgre.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"